### ISSUE TITLE
Quest 822 not in the list of Things for Barrens

### ISSUE THREAD

**Issue by Spwitas** [DFortun81/ATT-WRATH-Classic#33]
Heya,
For Wrath Classic variant, the third and final quest in Chen's Empty Keg series, [Chen's Empty Keg](https://www.wowhead.com/classic/quest=822/chens-empty-keg) is not listed among the Things in the Quest section (nor anywhere else) until it is actually taken from the quest giver. The first two are, but they lead to this quest which is the final one in the series.

**Comment by DFortun81** [comment]
Upon investigation, I determined that this quest is actually Repeatable. This means that as far as ATT cares, it won't display it until you're on the quest. As it doesn't get permanently marked completed, ATT opts to not show it as something you're missing. (otherwise the state for whether you have it or not will be lost when you reload your UI or log out)
